name: backend_embarque_solidario
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0-41.0.dev

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.1
  mysql1: ^0.20.0
  shelf_modular: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
